# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Record_Window(object):
    def setupUi(self, Record_Window):
        Record_Window.setObjectName("Record_Window")
        Record_Window.resize(505, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Record_Window)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Record_Window)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.record_frame = QtWidgets.QFrame(Record_Window)
        self.record_frame.setStyleSheet("#record_frame{border:3px solid #ff0000;}")
        self.record_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.record_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.record_frame.setObjectName("record_frame")
        self.verticalLayout.addWidget(self.record_frame)

        self.retranslateUi(Record_Window)
        QtCore.QMetaObject.connectSlotsByName(Record_Window)

    def retranslateUi(self, Record_Window):
        _translate = QtCore.QCoreApplication.translate
        Record_Window.setWindowTitle(_translate("Record_Window", "录制窗口"))
